version: "3"
services:
    app:
        image: inzynierka:python
        volumes: 
            - ./praca_inzynierska/backend:/var/www/app
        entrypoint: python application.py
        networks: 
            inzynierka: 
                ipv4_address: 172.21.3.2
        ports: 
            - 80:5000
    mysql:
        image: mysql:8
        networks: 
            inzynierka: 
                ipv4_address: 172.21.3.3 
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
            MYSQL_DATABASE: inzynierka
            
networks:
    inzynierka:
        ipam:
            driver: default
            config:
                - subnet: "172.21.3.0/24"